INSERT INTO department (code, department_name, description) VALUES 
('CS', 'Computer Science', 'Study of computation, algorithms, and software systems'),
('MATH', 'Mathematics', 'Science of numbers, quantity, and space'),
('PHY', 'Physics', 'Study of matter, energy, and fundamental forces'),
('CHEM', 'Chemistry', 'Science of substances and their interactions'),
('BIO', 'Biology', 'Study of living organisms and life processes'),
('ENVS', 'Environmental Science', 'Interdisciplinary study of environmental systems'),
('CSE', 'Computer Engineering', 'Combination of computer science and electrical engineering'),
('EE', 'Electrical Engineering', 'Study of electricity, electronics, and electromagnetism'),
('ME', 'Mechanical Engineering', 'Design and manufacturing of mechanical systems'),
('ENG', 'English', 'Study of literature, composition, and language'),
('HIST', 'History', 'Study of past events and human affairs'),
('PHIL', 'Philosophy', 'Study of fundamental questions about existence and knowledge'),
('BUS', 'Business Administration', 'Study of business operations and management'),
('ACC', 'Accounting', 'Measurement and analysis of financial information'),
('MKT', 'Marketing', 'Process of promoting and selling products'),
('NURS', 'Nursing', 'Profession focused on patient care and health maintenance'),
('PHARM', 'Pharmacy', 'Science of preparing and dispensing medical drugs'),
('ART', 'Fine Arts', 'Study and creation of visual artworks'),
('MUS', 'Music', 'Art form combining sound and silence'),
('THTR', 'Theater Arts', 'Study of dramatic performance and production');

INSERT INTO course (name, description, department_id) VALUES
('Introduction to Programming', 'Fundamentals of programming using Python', (SELECT id FROM department WHERE code = 'CS')),
('Data Structures & Algorithms', 'Study of efficient data organization and algorithms', (SELECT id FROM department WHERE code = 'CS')),
('Database Systems', 'Design and implementation of relational databases', (SELECT id FROM department WHERE code = 'CS')),
('Computer Networks', 'Principles of network architecture and protocols', (SELECT id FROM department WHERE code = 'CS')),
('Artificial Intelligence', 'Introduction to machine learning and AI concepts', (SELECT id FROM department WHERE code = 'CS')),
('Calculus I', 'Differential and integral calculus', (SELECT id FROM department WHERE code = 'MATH')),
('Linear Algebra', 'Vector spaces and matrix operations', (SELECT id FROM department WHERE code = 'MATH')),
('Discrete Mathematics', 'Logic, sets, and graph theory fundamentals', (SELECT id FROM department WHERE code = 'MATH')),
('Probability & Statistics', 'Probability theory and statistical methods', (SELECT id FROM department WHERE code = 'MATH')),
('Classical Mechanics', 'Newtonian physics and motion', (SELECT id FROM department WHERE code = 'PHY')),
('Electromagnetism', 'Maxwell equations and applications', (SELECT id FROM department WHERE code = 'PHY')),
('Quantum Physics', 'Fundamentals of quantum theory', (SELECT id FROM department WHERE code = 'PHY')),
('Thermodynamics', 'Heat, energy, and entropy principles', (SELECT id FROM department WHERE code = 'PHY')),
('General Chemistry', 'Basic principles of chemical reactions', (SELECT id FROM department WHERE code = 'CHEM')),
('Organic Chemistry', 'Structure and reactions of carbon compounds', (SELECT id FROM department WHERE code = 'CHEM')),
('Analytical Chemistry', 'Chemical analysis techniques', (SELECT id FROM department WHERE code = 'CHEM')),
('Physical Chemistry', 'Chemical thermodynamics and kinetics', (SELECT id FROM department WHERE code = 'CHEM')),
('Cell Biology', 'Structure and function of cells', (SELECT id FROM department WHERE code = 'BIO')),
('Genetics', 'Principles of heredity and variation', (SELECT id FROM department WHERE code = 'BIO')),
('Ecology', 'Organisms and their environments', (SELECT id FROM department WHERE code = 'BIO')),
('Evolutionary Biology', 'Theories of biological evolution', (SELECT id FROM department WHERE code = 'BIO')),
('Digital Logic Design', 'Boolean algebra and logic gates', (SELECT id FROM department WHERE code = 'CSE')),
('Computer Architecture', 'Processor design and organization', (SELECT id FROM department WHERE code = 'CSE')),
('Embedded Systems', 'Design of microprocessor-based systems', (SELECT id FROM department WHERE code = 'CSE')),
('Composition & Rhetoric', 'Academic writing techniques', (SELECT id FROM department WHERE code = 'ENG')),
('British Literature', 'Survey of major British works', (SELECT id FROM department WHERE code = 'ENG')),
('Creative Writing', 'Fiction and poetry writing workshop', (SELECT id FROM department WHERE code = 'ENG')),
('Principles of Management', 'Fundamentals of business organization', (SELECT id FROM department WHERE code = 'BUS')),
('Financial Accounting', 'Recording and reporting transactions', (SELECT id FROM department WHERE code = 'BUS')),
('Marketing Principles', 'Fundamentals of product promotion', (SELECT id FROM department WHERE code = 'BUS')),
('Anatomy & Physiology', 'Human body structure and function', (SELECT id FROM department WHERE code = 'NURS')),
('Clinical Nursing', 'Patient care techniques', (SELECT id FROM department WHERE code = 'NURS')),
('Pharmacology', 'Study of therapeutic drugs', (SELECT id FROM department WHERE code = 'NURS')),
('Music Theory', 'Fundamentals of musical structure', (SELECT id FROM department WHERE code = 'MUS')),
('Music History', 'Development of Western music', (SELECT id FROM department WHERE code = 'MUS')),
('Orchestration', 'Instrumentation and arrangement', (SELECT id FROM department WHERE code = 'MUS'));