INSERT INTO department (code, department_name, description) VALUES 
('CS', 'Computer Science', 'Study of computation, algorithms, and software systems'),
('MATH', 'Mathematics', 'Science of numbers, quantity, and space'),
('PHY', 'Physics', 'Study of matter, energy, and fundamental forces'),
('CHEM', 'Chemistry', 'Science of substances and their interactions'),
('BIO', 'Biology', 'Study of living organisms and life processes'),
('ENVS', 'Environmental Science', 'Interdisciplinary study of environmental systems'),
('CSE', 'Computer Engineering', 'Combination of computer science and electrical engineering'),
('EE', 'Electrical Engineering', 'Study of electricity, electronics, and electromagnetism'),
('ME', 'Mechanical Engineering', 'Design and manufacturing of mechanical systems'),
('ENG', 'English', 'Study of literature, composition, and language'),
('HIST', 'History', 'Study of past events and human affairs'),
('PHIL', 'Philosophy', 'Study of fundamental questions about existence and knowledge'),
('BUS', 'Business Administration', 'Study of business operations and management'),
('ACC', 'Accounting', 'Measurement and analysis of financial information'),
('MKT', 'Marketing', 'Process of promoting and selling products'),
('NURS', 'Nursing', 'Profession focused on patient care and health maintenance'),
('PHARM', 'Pharmacy', 'Science of preparing and dispensing medical drugs'),
('ART', 'Fine Arts', 'Study and creation of visual artworks'),
('MUS', 'Music', 'Art form combining sound and silence'),
('THTR', 'Theater Arts', 'Study of dramatic performance and production');